version: "3.9"

services:
  circle-detector:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: circle-detector-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./extracted_circles:/app/extracted_circles
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - circle-net

networks:
  circle-net:
    driver: bridge
